apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: container-image-registry-ingress
#  namespace: container-image-registry
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
#  tls:
#  - hosts:
#      - container-image-registry
#    secretName: container-image-registry-ingress-cert
  rules:
  - host: docker-registry
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docker-registry
            port:
              number: 5000
