apiVersion: v1
kind: PersistentVolume
metadata:
  name: container-registry-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-registry-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
