apiVersion: v1
kind: PersistentVolume
metadata:
  name: container-image-registry
  namespace: container-image-registry
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: container-image-registry-node
            operator: In
            values:
            - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-image-registry
  namespace: container-image-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
